/* eslint-disable @next/next/no-html-link-for-pages */
import { _customer } from "@/types";
import Head from "next/head";

const demoCall: _customer = {
  first_name: "Flossy",
  last_name: "Fynan",
  gender: "Female",
  email: "ffynan1@surveymonkey.com",
  phone_number: "105-166-8295",
  address: "9220 Delaware Lane",
  card_number: "4041592692905077",
  order_total: "$55.07",
  order_date: "11/02/19",
  product_category: "pets",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Mock Customer API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossOrigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossOrigin="anonymous"
          async
        ></script>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>
      <div className="container">
        <div className="row" id="homepage_row">
          <div className="col-lg-6 text-center">
            <h1>Mock Customer API</h1>
            <p id="homepage_tag">
              Easily fetch randomly generated customers from a database
              consisting of over 10,000 fake records
            </p>
            <a
              href="/api"
              className="api-link-btn"
              title="Fetch a random customer"
            >
              GET <b>/api</b>
            </a>
          </div>
          <div className="col-lg-6" id="example_return_col">
            <p>
              Exmaple response <i>(JSON format)</i>
            </p>
            <pre id="example_request">
              {JSON.stringify(demoCall, undefined, 2)}
            </pre>
          </div>
        </div>
        <hr></hr>
        <p>There are several valid url queries</p>
        <ul>
          <li className="query-li">
            <b className="url-query">
              <code>?product</code>
            </b>
            <p>
              Filters customer records by type of product purchased. Returns a
              single random record unless limit query is specified.
            </p>
            <ol>
              <li>Apparel</li>
              <li>Arts</li>
              <li>Automobiles</li>
              <li>Books</li>
              <li>Business</li>
              <li>Energy</li>
              <li>Family</li>
              <li>Food</li>
              <li>Garden</li>
              <li>Healthcare</li>
              <li>Home Improvement</li>
              <li>Pets</li>
              <li>Sporting Goods</li>
              <li>Travel</li>
            </ol>
            <div>
              <i>
                Example: fetch all customer records that have a product category
                of home improvement{" "}
                <a href="/api?product=home-improvement" className="api-link">
                  /api?product=home-improvement
                </a>
              </i>
            </div>
          </li>
          <li>
            <b className="url-query">
              <code>?limit</code>
            </b>
            <p>
              Set the max number of records to be returned. Limit cannot be
              greater than 1000 or less than 2. If the current query has less
              records stored than the limit specified, all of the records will
              be returned. This query will return a random array of records.
            </p>
            <div>
              <i>
                Example: fetch up to 731 random customer records
                <a href="/api?limit=731" className="api-link">
                  /api?limit=731
                </a>
              </i>
            </div>
            <div>
              <i>
                Example: fetch up to 365 customer records that have purchased a
                product in the pets category
                <a
                  href="/api?product=home-improvement&limit=365 "
                  className="api-link"
                >
                  /api?product=home-improvement&limit=365
                </a>
              </i>
            </div>
          </li>
        </ul>
      </div>
    </>
  );
}
