/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/no-html-link-for-pages */
import { _customer } from "@/types";
import Head from "next/head";

const demoCall: _customer = {
  first_name: "Flossy",
  last_name: "Fynan",
  gender: "Female",
  email: "ffynan1@surveymonkey.com",
  phone_number: "105-166-8295",
  address: "9220 Delaware Lane",
  card_number: "4041592692905077",
  order_total: "$55.07",
  order_date: "11/02/19",
  product_category: "pets",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Mock Customer API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossOrigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossOrigin="anonymous"
          async
        ></script>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>
      <div className="container">
        <div className="row" id="homepage_row">
          <div className="col-lg-6 text-center">
            <img
              src="/person-vcard.svg"
              width={100}
              height={100}
              alt="person traits icon"
            />
            <h1>Mock Customer API</h1>
            <p id="homepage_tag">
              Easily fetch randomly generated customers from a database
              consisting of over 20,000 fake records
            </p>
            <a
              href="/api"
              className="api-link-btn"
              title="Fetch a random customer"
            >
              GET <b>/api</b>
            </a>
          </div>
          <div className="col-lg-6" id="example_return_col">
            <p>
              Exmaple response <i>(JSON format)</i>
            </p>
            <pre id="example_request">
              {JSON.stringify(demoCall, undefined, 2)}
            </pre>
          </div>
        </div>
        <hr></hr>
        <p>There are several valid url queries</p>
        <ul>
          <li className="query-li">
            <b className="url-query">
              <code>?product</code>
            </b>
            <p>
              Filters customer records by type of product purchased. Returns a
              single random record unless limit query is specified.
            </p>
            <ol>
              <li>Apparel</li>
              <li>Arts</li>
              <li>Automobiles</li>
              <li>Books</li>
              <li>Business</li>
              <li>Energy</li>
              <li>Family</li>
              <li>Food</li>
              <li>Garden</li>
              <li>Healthcare</li>
              <li>Home Improvement</li>
              <li>Pets</li>
              <li>Sporting Goods</li>
              <li>Travel</li>
            </ol>
            <div>
              <i>
                Example: fetch all customer records that have a product category
                of home improvement{" "}
                <a href="/api?product=home-improvement" className="api-link">
                  /api?product=home-improvement
                </a>
              </i>
            </div>
          </li>
          <li>
            <b className="url-query">
              <code>?limit</code>
            </b>
            <p>
              Set the max number of records to be returned. Limit cannot be
              greater than 1000 or less than 2. Note that product query cannot
              be used alongside limit query.
            </p>
            <div>
              <i>
                Example: fetch up to 731 random customer records
                <a href="/api?limit=731" className="api-link">
                  /api?limit=731
                </a>
              </i>
            </div>
          </li>
        </ul>
        <div id="awoldt_tag">
          <a
            href="https://awoldt.com/"
            target="_blank"
            rel="noreferrer"
            style={{ textDecoration: "none", color: "#6c757d" }}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              className="bi bi-brush"
              viewBox="0 0 16 16"
              style={{ marginRight: "5px" }}
            >
              <path d="M15.825.12a.5.5 0 0 1 .132.584c-1.53 3.43-4.743 8.17-7.095 10.64a6.067 6.067 0 0 1-2.373 1.534c-.018.227-.06.538-.16.868-.201.659-.667 1.479-1.708 1.74a8.118 8.118 0 0 1-3.078.132 3.659 3.659 0 0 1-.562-.135 1.382 1.382 0 0 1-.466-.247.714.714 0 0 1-.204-.288.622.622 0 0 1 .004-.443c.095-.245.316-.38.461-.452.394-.197.625-.453.867-.826.095-.144.184-.297.287-.472l.117-.198c.151-.255.326-.54.546-.848.528-.739 1.201-.925 1.746-.896.126.007.243.025.348.048.062-.172.142-.38.238-.608.261-.619.658-1.419 1.187-2.069 2.176-2.67 6.18-6.206 9.117-8.104a.5.5 0 0 1 .596.04zM4.705 11.912a1.23 1.23 0 0 0-.419-.1c-.246-.013-.573.05-.879.479-.197.275-.355.532-.5.777l-.105.177c-.106.181-.213.362-.32.528a3.39 3.39 0 0 1-.76.861c.69.112 1.736.111 2.657-.12.559-.139.843-.569.993-1.06a3.122 3.122 0 0 0 .126-.75l-.793-.792zm1.44.026c.12-.04.277-.1.458-.183a5.068 5.068 0 0 0 1.535-1.1c1.9-1.996 4.412-5.57 6.052-8.631-2.59 1.927-5.566 4.66-7.302 6.792-.442.543-.795 1.243-1.042 1.826-.121.288-.214.54-.275.72v.001l.575.575zm-4.973 3.04.007-.005a.031.031 0 0 1-.007.004zm3.582-3.043.002.001h-.002z" />
            </svg>
            Made by awoldt
          </a>
        </div>
      </div>
    </>
  );
}
